### ISSUE TITLE
Check that the size of About field is at least 50 chars long

### ISSUE THREAD

**Issue by sdelamo** [grails-samples/grails-slack#8]
We want to ensure about texts provide enough descriptions to allow users requests to be properly reviewed

https://github.com/grails-samples/grails-slack/blob/master/app/grails-app/controllers/org/grails/im/plugins/ui/controllers/RequestInviteCommand.groovy#L15

if the command object fails, the users should be informed via flash.message grails capabilities

**Comment by ilopmar** [comment]
Done in #10
